services:
    - type: web
      name: chronos
      runtime: python
      buildCommand: |
          npm --prefix web ci &&
          npm --prefix web run build &&
          pip install -r requirements.txt
      startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
      envVars:
          - key: PYTHON_VERSION
            value: 3.14.0
