"""drop events table

Revision ID: 0efb07e45705
Revises: 1e3a01afc780
Create Date: 2026-03-26 17:56:02.473029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0efb07e45705'
down_revision: Union[str, Sequence[str], None] = '1e3a01afc780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_session_id'), table_name='events')
    op.drop_table('events')
    op.add_column('sessions', sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False))
    op.add_column('sessions', sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False))
    op.add_column('sessions', sa.Column('set_duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'set_duration')
    op.drop_column('sessions', 'end_datetime')
    op.drop_column('sessions', 'start_datetime')
    op.create_table('events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', postgresql.ENUM('STARTED', 'PAUSED', 'RESUMED', 'COMPLETED', name='eventtype'), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('events_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    op.create_index(op.f('ix_events_session_id'), 'events', ['session_id'], unique=False)
    # ### end Alembic commands ###
